### ISSUE TITLE
Refatoração do método de download do Pdf

### ISSUE THREAD

**Issue by pedro-prp** [BotLino/Lino-Webcrawler-Matricula#6]
**Descrição**

A issue tem como objetivo adicionar um método de check para o serviço não realizar o download repetido do pdf.

**Tarefas**

- [x] Checar se o pdf já está na pasta de Download.

**Critérios de aceitação**

- [x] Não realizar o download do pdf caso já esteja na pasta.

**Comment by guilacerda** [comment]
@pedro-prp essa issue ta aberta no repositório principal também?
